### PR TITLE
Add possibility for GroupValueRead at startup

### LINKED ISSUE #54: Add possibility for GroupValueRead at startup
**Is your feature request related to a problem? Please describe.**
If I understand correctly, knx-exporter receives data from KNX bus only after the following two events:
1. if a KNX module sends a GroupValueWrite because it has configured a cyclic sending or because the state of an associated group object changed.
2. if knx-exporter (or sombody else) issued a GroupValueRead beforehand

In my opinion there is one use case missing:
* when knx-exporter is started it should be able to send GroupValueRead telegrams to all the exported group addresses in order to get the current status of all the configured metrics.

This is needed in various situations:
1. when setting up knx-exporter, most probably one has to restart it several times until the configuration is ok. currently the states get lost everytime.
2. when extending your KNX installation one needs to change the knx-exporter config and therefore restart as well
3. when the connection to the KNX IP interface is lost and knx-exporter is restarted in order to reconnect, e.g. by `-r exit`

**Describe the solution you'd like**
A configuration option on `AddressConfigs` level could be introduced that specifies for a given group address that it should be read when knx-exporter is started, like: `ReadStartup: true`

Care must be taken to not overwhelm the KNX bus with GroupValueRead telegrams in big installations, when knx-exporter starts.

Therefore an additional configuration option on global level or maybe on `Connection` level could be introduced, that specifies a maximum read frequency, e.g. `StartupReadFrequency: 100ms`.

**Describe alternatives you've considered**
I think that currently the only alternatives to sync allt he states after a restart are:
1. configure `ReadActive: true` and an according `MaxAge` in order that group addresses get read periodically, also after a restart of knx-exporter
2. configure all the KNX modules on the bus to send their states cyclically - but this is not always possible / not all modules allow that for all their states

**Additional context**
If this proposal is interesting, I would like to offer help in the implementation or in testing. I am open to a discussion on how to improve this further.

@chr-fritz thx for the work so far, this helped me find some tricky errors in my KNX installation.

### PR DESCRIPTION
**Pull request by nomisim**
This adds a go routing that performs the startup read operation. It is inspired by the poller go routine.

The startup read routine sends GroupValueRead telegrams to all group addresses configured with `ReadStartup: true` (the default is false). By default the GroupValueRead telegrams are sent in a 200ms interval, in order to not everwhelm the bus. The interval can be changed by adopting the `ReadStartupInterval: 200ms` configuration parameter in the global section of the config file.

If this is acceptable I can also update README.md to have it documented - just let me know.

Resolves #54

### CODE REVIEW

**Review by chr-fritz — CHANGES_REQUESTED** [review]
First of all, a big thank you for the PR. Apart from the three minor change requests, I have two major ones before I merge the PR:

First, please build suitable tests for the most important parts, `Run()` and `getMetricsToRead(config *Config) GroupAddressConfigSet`, from the `startupReader` and second, add new configuration options to `README.md`.

**Comment by nomisim** [comment]
This took a while now, as I was on vacation in between.
However, I managed to update the code today:
* integrated the fixes you proposed
* updated the README.md to include new config options
* addedd tests for `Run()` and `getMetricsToRead(config *Config) GroupAddressConfigSet` from the startupReader
* merged with upstream
Hope this goes into the right direction - let me know what you think.

**Comment by chr-fritz** [comment]
No problem, I hope the holiday was relaxing.

Thanks for the feature, I'll merge itl.

**Comment by nomisim** [comment]
Thanks, sure no problem. I am looking forward to the TCP feature as well.

**Pull request merged**
